name: bandeira
description: Official Dart/Flutter client SDK for Bandeira feature flag service
version: 0.2.0
homepage: https://github.com/felipekafuri/bandeira-sdks
repository: https://github.com/felipekafuri/bandeira-sdks/tree/main/dart
issue_tracker: https://github.com/felipekafuri/bandeira-sdks/issues

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  http: ^1.2.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
